import pytest
from math import isclose
from quantities.quantity_type import QuantityType

def test_prefix_unit_convert():
    assert isclose(QuantityType.pri_unit.from_pri_unit(1), 1e+0)
    assert isclose(QuantityType.pri_unit.to_pri_unit(1), 1e+0)

    assert isclose(QuantityType.d_unit.from_pri_unit(1), 1e+1)
    assert isclose(QuantityType.d_unit.to_pri_unit(1), 1e-1)
    assert isclose(QuantityType.c_unit.from_pri_unit(1), 1e+2)
    assert isclose(QuantityType.c_unit.to_pri_unit(1), 1e-2)
    assert isclose(QuantityType.m_unit.from_pri_unit(1), 1e+3)
    assert isclose(QuantityType.m_unit.to_pri_unit(1), 1e-3)
    assert isclose(QuantityType.mu_unit.from_pri_unit(1), 1e+6)
    assert isclose(QuantityType.mu_unit.to_pri_unit(1), 1e-6)
    assert isclose(QuantityType.n_unit.from_pri_unit(1), 1e+9)
    assert isclose(QuantityType.n_unit.to_pri_unit(1), 1e-9)
    assert isclose(QuantityType.p_unit.from_pri_unit(1), 1e+12)
    assert isclose(QuantityType.p_unit.to_pri_unit(1), 1e-12)
    assert isclose(QuantityType.f_unit.from_pri_unit(1), 1e+15)
    assert isclose(QuantityType.f_unit.to_pri_unit(1), 1e-15)
    assert isclose(QuantityType.a_unit.from_pri_unit(1), 1e+18)
    assert isclose(QuantityType.a_unit.to_pri_unit(1), 1e-18)
    assert isclose(QuantityType.z_unit.from_pri_unit(1), 1e+21)
    assert isclose(QuantityType.z_unit.to_pri_unit(1), 1e-21)
    assert isclose(QuantityType.y_unit.from_pri_unit(1), 1e+24)
    assert isclose(QuantityType.y_unit.to_pri_unit(1), 1e-24)

    assert isclose(QuantityType.da_unit.from_pri_unit(1), 1e-1)
    assert isclose(QuantityType.da_unit.to_pri_unit(1), 1e+1)
    assert isclose(QuantityType.h_unit.from_pri_unit(1), 1e-2)
    assert isclose(QuantityType.h_unit.to_pri_unit(1), 1e+2)
    assert isclose(QuantityType.k_unit.from_pri_unit(1), 1e-3)
    assert isclose(QuantityType.k_unit.to_pri_unit(1), 1e+3)
    assert isclose(QuantityType.M_unit.from_pri_unit(1), 1e-6)
    assert isclose(QuantityType.M_unit.to_pri_unit(1), 1e+6)
    assert isclose(QuantityType.G_unit.from_pri_unit(1), 1e-9)
    assert isclose(QuantityType.G_unit.to_pri_unit(1), 1e+9)
    assert isclose(QuantityType.T_unit.from_pri_unit(1), 1e-12)
    assert isclose(QuantityType.T_unit.to_pri_unit(1), 1e+12)
    assert isclose(QuantityType.P_unit.from_pri_unit(1), 1e-15)
    assert isclose(QuantityType.P_unit.to_pri_unit(1), 1e+15)
    assert isclose(QuantityType.E_unit.from_pri_unit(1), 1e-18)
    assert isclose(QuantityType.E_unit.to_pri_unit(1), 1e+18)
    assert isclose(QuantityType.Z_unit.from_pri_unit(1), 1e-21)
    assert isclose(QuantityType.Z_unit.to_pri_unit(1), 1e+21)
    assert isclose(QuantityType.Y_unit.from_pri_unit(1), 1e-24)
    assert isclose(QuantityType.Y_unit.to_pri_unit(1), 1e+24)
    